# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c45c4fb7350e014a8893c714c93f788d70a8c445af9e9c005f98fafe1bfc48b3b8c6ff2c9188a2ad3c9f395aff252fe5c745bc8f2520b5d87746dc36b8fbb3b

test:
  secret_key_base: 99330f5f9cae1ed89eaebb5c8de8c540c67651e5313c3a1c5c972d7a004166b4fa83e1f227637e19c9b0592f8cbd8b1427cef968daf9dff0e5d74d98a6b23b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
